### PR TITLE
Make the real unique category tree

### PR DESCRIPTION
**Pull request by janikjan**
Hi :)

I just want for Prestashop to respect different tree with same name of last category to be unique.

I hope you can understand me.

I have main categories:
1. E-cigarettes
2. Atomizers
etc

E-cigarettes have sub-categories which is actually name of producers:
- Innokin
- Joyetech
- Kangertech
  etc.

But also Atomizers have sub-categories based on name of producers. But as you can see it is in different tree:
- Innokin
- Joyetech
- Kangertech

So link to category E-cigarettes and sub-category Innokin will be: www.bezpopelniku.cz/e-cigarettes/innokin
Link to category atomizers and sub-category Innokin will be: www.bezpopelniku.cz/atomizers/innokin

But here is the problem! As you can see this is 2 different pages, at least it should be 2 different pages with differents products (one is category with e-cigarettes and the second with atomizers).

But when I click to second link www.bezpopelniku.cz/atomizers/innokin I will be redirected to the first link www.bezpopelniku.cz/e-cigarettes/innokin which is not correct.
So it seems that Prestashop or your module does not make any for category tree URLs and as unique point is only the last category (but not the whole URL).

That is my question or please for fix because it is not good from my point of view. 
I hope you can make this to work like it should work.

### CODE REVIEW

**Comment by ghost** [comment]
What is this PR?  ..

**Comment by janikjan** [comment]
Hello ZiZuu,

I am new in github so I made a mistake and first time I added my issues or opinion to improve your module here and not to the right place. So I think this comment here is not needed anymore.

Sorry for that but I am still learning.

**Comment by ghost** [comment]
This is not comment, but a pull request. A PR is a code contribution to a project, a request to merge a given bug fix or enhancement into a project. 

For your need an issue is the right tool.

I think you can close this PR ;)

**Comment by janikjan** [comment]
I understand now. I thought that you think I make here PR like marketing :-) :-). Ok, now it is clear I am closing it here.

**Pull request closed without merging**
