### PR TITLE
ZiZuu clean URLs

### PR DESCRIPTION
**Pull request by ghost**
Fixed getCategoryLink method: …
    - passed missing $id_shop to the getLangLink and createUrl methods
    - remove only root and current category from the URL

Fixed canonicalRedirection() …
    - canonicalRedirection has to remove rewrite ids from _GET before
      redirect, as it already does in the FrontController for ordinary id_*

### CODE REVIEW

**Comment by vinzter** [comment]
Your module or the one from Lebioda branch doesn't work on prestashop 1.6 but original file from https://github.com/Ha99y/PrestaShop-modules-CleanURLs works on 1.6.0.8

Problem seems to come from override classes Dispatcher.php an Link.php

**Comment by ghost** [comment]
very strange .. as we have this code running on our server ... ww'll investigate thank you

**Comment by ghost** [comment]
Can you be more explicit plz? .. What is not working? Error? wrong behavior?  Any info is welcome

**Comment by vinzter** [comment]
The category and cms redirection are working, what is not working is the product redirection.
The url is good in the browser but instead of the product page and the product infos I get a 404 template page.

It seems like there is a problem in the class Dispatcher.php, because from what i can see the first problem is that the switch($route['controller']) doesn't return anything so I get to if(empty($findRoute)) and that's where there is a second problem.
But if I comment the switch function and just leave "$findRoute = $route; break;" then all is working categories, cms, products

I don't know if this will help you, let me know. For the moment i have it working like this.

**Comment by ghost** [comment]
It's strange .. as we have ot working on our online shop .. we'll try to
give a deeper look in the next days, tnx

Cordialmente,

Massimo -- _the ZiZuu staff_

2014-06-27 20:51 GMT+02:00 vinzter notifications@github.com:

**Comment by mnwalker** [comment]
Hi,
I know old but incase this helps anyone, had a very similar issue with products showing 404.
Turned out the dispatcher was searching for the rewrite with the .html on the end while the database had no .html.

Fixed version over here https://github.com/awcode/PrestaShop-modules-CleanURLs

**Comment by ghost** [comment]
Thank you . .will look as soon as possible .. would you like to put a pull
request?

Cordialmente,
Massimo -- _the ZiZuu staff_

2015-03-04 8:34 GMT+01:00 Mark Walker notifications@github.com:

**Pull request closed without merging**
